export const type = {

    OPEN_NOTE: 'OPEN_NOTE',
    UPDATE_PAGINATION: 'UPDATE_PAGINATION',

    SET_NOTE_POSITION: 'SET_NOTE_POSITION',

    FETCH_DATA: 'FETCH_DATA',

    INPUT_VISIBLE: 'INPUNT_VISIBLE',

    TOGGLE_DRAWER: 'TOGGLE_DRAWER',
    CLOSE_DRAWER: 'CLOSE_DRAWER',
    OPEN_DRAWER: 'OPEN_DRAWER',

    TOGGLE_LABELS_MODAL: 'TOGGLE_LABELS_MODAL',

    TOGGLE_SELECT_NOTE: 'TOGGLE_SELECT_NOTE',
    RECTANGLE_SELECT_NOTES: 'RECTANGLE_SELECT_NOTES',
    CHANGE_NOTE_COLOR: 'CHANGE_NOTE_COLOR',
    CLEAR_SELECTED_NOTES: 'CLEAR_SELECTED_NOTES',

    FETCH_LABELS_REQUEST: "FETCH_LABELS_REQUEST",
    FETCH_LABELS_SUCCESS: "FETCH_LABELS_SUCCESS",
    FETCH_LABELS_FAILURE: "FETCH_LABELS_FAILURE",

    UPDATE_LABEL: 'UPDATE_LABEL',
    UPDATE_LABELS_REQUEST: "UPDATE_LABELS_REQUEST",
    UPDATE_LABELS_SUCCESS: "UPDATE_LABELS_SUCCESS",
    UPDATE_LABELS_FAILURE: "UPDATE_LABELS_FAILURE",

    DELETE_LABEL: 'DELETE_LABEL',
    DELETE_LABELS_REQUEST: "DELETE_LABELS_REQUEST",
    DELETE_LABELS_SUCCESS: "DELETE_LABELS_SUCCESS",
    DELETE_LABELS_FAILURE: "DELETE_LABELS_FAILURE",

    ADD_LABEL: 'ADD_LABEL',
    CREATE_LABELS_REQUEST: "CREATE_LABELS_REQUEST",
    CREATE_LABELS_SUCCESS: "CREATE_LABELS_SUCCESS",
    CREATE_LABELS_FAILURE: "CREATE_LABELS_FAILURE",


    FETCH_NOTES_REQUEST: "FETCH_NOTES_REQUEST",
    FETCH_NOTES_SUCCESS: "FETCH_NOTES_SUCCESS",
    FETCH_NOTES_FAILURE: "FETCH_NOTES_FAILURE",

    FETCH_COLORS_REQUEST: "FETCH_COLORS_REQUEST",
    FETCH_COLORS_SUCCESS: "FETCH_COLORS_SUCCESS",
    FETCH_COLORS_FAILURE: "FETCH_COLORS_FAILURE",

    FETCH_NOTE_REQUEST: "FETCH_NOTE_REQUEST",
    FETCH_NOTE_SUCCESS: "FETCH_NOTE_SUCCESS",
    FETCH_NOTE_FAILURE: "FETCH_NOTE_FAILURE",

    UPDATE_NOTE: 'UPDATE_NOTE',
    UPDATE_NOTES_REQUEST: "UPDATE_NOTES_REQUEST",
    UPDATE_NOTES_SUCCESS: "UPDATE_NOTES_SUCCESS",
    UPDATE_NOTES_FAILURE: "UPDATE_NOTES_FAILURE",

    DELETE_NOTE: 'DELETE_NOTE',
    DELETE_NOTES_REQUEST: "DELETE_NOTES_REQUEST",
    DELETE_NOTES_SUCCESS: "DELETE_NOTES_SUCCESS",
    DELETE_NOTES_FAILURE: "DELETE_NOTES_FAILURE",

    ADD_NOTE: 'ADD_NOTE',
    ADD_NOTES: 'ADD_NOTES',
    CREATE_NOTES_REQUEST: "CREATE_NOTES_REQUEST",
    CREATE_NOTES_SUCCESS: "CREATE_NOTES_SUCCESS",
    CREATE_NOTES_FAILURE: "CREATE_NOTES_FAILURE"


};
